
[Levels]
	#What is the global max level
	#Range: 1 ~ 1000000
	maxLevel = 999
	#What is the xp increase per level ( baseXp + level * xpPerLevel )
	#Range: 1 ~ 1000000
	xpIncreasePerLevel = 50
	#What is the baseXp to reach level 2 ( baseXp + level * xpPerLevel )
	#Range: 1 ~ 1000000
	baseXp = 250

["Armor Level Requirements"]
	#Level Required to wear Iron Equipment
	#Range: 1 ~ 1000000
	levelReqIronArmor = 20
	#Level Required to wear Leather Equipment
	#Range: 1 ~ 1000000
	levelReqLeatherArmor = 5
	#Level Required to wear Diamond Equipment
	#Range: 1 ~ 1000000
	levelReqDiamondArmor = 40
	#Level Required to wear Turtle Equipment
	#Range: 1 ~ 1000000
	levelReqTurtleArmor = 10
	#Level Required to wear Chain Equipment
	#Range: 1 ~ 1000000
	levelReqChainArmor = 10
	#Level Required to wear Gold Equipment
	#Range: 1 ~ 1000000
	levelReqGoldArmor = 30

["Tool Level Requirements"]
	#Level Required to use Stone Tools
	#Range: 1 ~ 1000000
	levelReqStoneTool = 5
	#Level Required to use Golden Tools
	#Range: 1 ~ 1000000
	levelReqGoldTool = 30
	#Level Required to use Wooden Tools
	#Range: 1 ~ 1000000
	levelReqWoodTool = 1
	#Level Required to use Diamond Tools
	#Range: 1 ~ 1000000
	levelReqDiamondTool = 40
	#Level Required to use Iron Tools
	#Range: 1 ~ 1000000
	levelReqIronTool = 20

["Weapon Level Requirements"]
	#Level Required to use Iron Weapons
	#Range: 1 ~ 1000000
	levelReqIronWeapon = 20
	#Level Required to use Wooden Weapons
	#Range: 1 ~ 1000000
	levelReqWoodWeapon = 1
	#Level Required to use Stone Weapons
	#Range: 1 ~ 1000000
	levelReqStoneWeapon = 5
	#Level Required to use Golden Weapons
	#Range: 1 ~ 1000000
	levelReqGoldWeapon = 30
	#Level Required to use Diamond Weapons
	#Range: 1 ~ 1000000
	levelReqDiamondWeapon = 40

[Multipliers]
	#How much xp everyone gains in Repairing (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	repairingMultiplier = 1.0
	#How much xp everyone gains on Peaceful Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	peacefulMultiplier = 0.3333333333333333
	#How much xp everyone gains in Flying (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	flyingMultiplier = 1.0
	#How much xp everyone gains in Swimming (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	swimmingMultiplier = 1.0
	#How much xp everyone gains on Easy Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	easyMultiplier = 0.6666666666666666
	#How much xp everyone gains on Hard Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	hardMultiplier = 1.3333333333333333
	#How much xp everyone gains in Mining (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	miningMultiplier = 10.0
	#How much xp everyone gains in Building (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	buildingMultiplier = 1.0
	#How much xp everyone gains on Normal Difficulty (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	normalMultiplier = 1.0
	#How much xp everyone gains in Farming (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	farmingMultiplier = 1.0
	#How much xp everyone gains in Agility (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	agilityMultiplier = 1.0
	#How much xp everyone gains in Excavation (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	excavationMultiplier = 1.0
	#How much xp everyone gains in Archery (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	archeryMultiplier = 1.0
	#How much xp everyone gains in Crafting (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	craftingMultiplier = 1.0
	#How much xp everyone gains in Fishing (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	fishingMultiplier = 1.0
	#How much xp everyone gains in Endurance (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	enduranceMultiplier = 1.0
	#How much xp everyone gains in Combat (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	combatMultiplier = 1.0
	#How much xp everyone gains (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	globalMultiplier = 1.0
	#How much xp everyone gains in Woodcutting (1 = normal, 2 = twice as much)
	#Range: 0.0 ~ 1000.0
	woodcuttingMultiplier = 1.0

[GUI]
	#If Off, xp drops will no longer stack with each other
	stackXpDrops = true
	#GUI bar position Y (Height, 0 is top, 1 is bottom (1 is probably invisible due to clipping) )
	#Range: 0.0 ~ 1.0
	barOffsetY = 0.0
	#GUI bar position X (Width)
	#Range: 0.0 ~ 1.0
	barOffsetX = 0.5
	#If Off, xp drops will no longer appear
	showXpDrops = true

["Breaking Speed"]
	#How many blocks it takes to reach 0 Break Speed (will get capped by Minimum Breaking Speed)
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	blocksToUnbreakableY = 1000.0
	#How much your cutting speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	woodcuttingBonusSpeed = 1.0
	#How much your farming speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	farmingBonusSpeed = 1.0
	#How much your digging speed increases per level in (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	excavationBonusSpeed = 1.0
	#Minimum Breaking Speed (1 is Original speed, 0.5 is half)
	#Range: 0.0 ~ 100.0
	minBreakSpeed = 0.5
	#How much your mining speed increases per level (1 = 1% increase per level)
	#Range: 0.0 ~ 10.0
	miningBonusSpeed = 1.0

[Mining]
	#Hardest considered block (1 hardness = 1 build/remove xp. 0 = no xp for block hardness, 30 means obsidian caps at 30xp per block.)
	#Range: 0.0 ~ 1000000.0
	blockHardnessLimit = 250.0

[Building]
	#Every how many levels you gain an extra block of reach
	#Range: 0 ~ 1000
	levelsPerBlockReach = 25

[Agility]
	#Every how many levels you gain an extra block of jumping height while Crouching
	#Range: 0 ~ 1000
	levelsCrouchJumpBoost = 33
	#Maximum chance to save each point of fall damage (100 = no fall damage)
	#Range: 0.0 ~ 100.0
	maxFallSaveChance = 64.0
	#How much jump boost can you gain max (above 0.33 makes you take fall damage)
	#Range: 0.0 ~ 100.0
	maxJumpBoost = 0.33
	#How much speed boost you can get from Agility (Incredibly sensitive, default 0.1)
	#Range: 0.0 ~ 10.0
	maxSpeedBoost = 0.1
	#How much your chance to save each point of fall damage increases per level (1 = 1% increase per Level)
	#Range: 0.0 ~ 100.0
	saveChancePerLevel = 64.0
	#Every how many levels you gain an extra block of jumping height while Sprinting
	#Range: 0 ~ 1000
	levelsSprintJumpBoost = 50
	#How much speed boost you get from each level (Incredibly sensitive, default 0.0005)
	#Range: 0.0 ~ 10.0
	speedBoostPerLevel = 5.0E-4

[Endurance]
	#Per how many levels you gain 1 Max Heart
	#Range: 0 ~ 1000
	levelsPerHeart = 10
	#How many Bonus Max Hearts you can have
	#Range: 0 ~ 1000
	maxHeartCap = 20
	#How much endurance is max (100 = god mode)
	#Range: 0.0 ~ 100.0
	maxEndurance = 50.0
	#How much endurance you gain per level (1 = 1% per level)
	#Range: 0.0 ~ 100.0
	endurancePerLevel = 0.25

[Combat]
	#Per how many levels you gain 1 Extra Damage
	#Range: 0 ~ 1000
	levelsPerDamage = 20

[Repairing]
	#Anvil combination limits enchantments to this level
	#Range: 0 ~ 255
	maxEnchantLevel = 255
	#Vanilla starts at 50, hence: (50 - [this] * level)
	#Range: 0.0 ~ 100.0
	anvilCostReductionPerLevel = 0.25
	#Bonus repair durability per level (100 = twice as much repair per level)
	#Range: 0.0 ~ 100.0
	anvilFinalItemBonusRepaired = 1.0
	#How many levels per each Enchantment Level Bypass above max level enchantment can support in vanilla
	#Range: 0 ~ 1000
	levelsPerOneEnchantBypass = 50
	#Anvil combination limits enchantments to max level set in this config
	bypassEnchantLimit = true
	#Max Percentage chance to return each Material
	#Range: 0.0 ~ 100.0
	maxSalvageMaterialChance = 80.0
	#Max amount of levels enchants are able to go above max vanilla level
	#Range: 0 ~ 1000
	maxEnchantmentBypass = 2
	#Each Enchantment Save Chance per Level
	#Range: 0.0 ~ 100.0
	enchantSaveChancePerLevel = 0.9
	#What is the chance to Bypass a max enchant level (provided you got the skill to do so)
	#Range: 0.0 ~ 100.0
	upgradeChance = 50.0
	#Vanilla caps at 50, at around 30 vanilla you can no longer anvil the item again. allows unlocking infinite Anvil uses.
	#Range: 0 ~ 50
	anvilFinalItemMaxCostToAnvil = 10
	#Chance to not break anvil, 100 = twice the value, half the chance per Level.
	#Range: 0.0 ~ 100.0
	extraChanceToNotBreakAnvilPerLevel = 1.0
	#What is the chance to Reduce a level after a Upgrade chance fails (100 = everytime you fail bypass, enchant level goes down by 1)
	#Range: 0.0 ~ 100.0
	failedUpgradeKeepLevelChance = 50.0
	#Max Percentage chance to return each Enchantment Level
	#Range: 0.0 ~ 100.0
	maxSalvageEnchantChance = 90.0
	#false = Upgrade Chance if only rolled if you are trying to upgrade your item ABOVE vanilla max level. true = you ALWAYS have an upgrade chance level.
	alwaysUseUpgradeChance = false

[Swimming]
	#Underwater Nightvision Unlock Level
	#Range: 0 ~ 1000000
	nightvisionUnlockLevel = 25

